/*
 * Copyright (C) 2024 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"
#include "AutoGeneratedTranscriptionManager.h"
#include "AutomaticTranscriptionGenerator.h"

#include "SharedCARingBuffer.h"
#include "Logging.h"
#include <wtf/LoggerHelper.h>

#if ENABLE(GPU_PROCESS) && ENABLE(VIDEO)

#include "AutoGeneratedTranscriptionManagerMessages.h"
#include "AutoGeneratedTranscriptionManagerProxyMessages.h"


namespace WebKit {
AutoGeneratedTranscriptionManager::AutoGeneratedTranscriptionManager(IPC::Connection* connection)
: m_connection(connection)
{
    
}

void AutoGeneratedTranscriptionManager::registerClient(WebCore::MediaPlayerIdentifier identifier)
{
    ASSERT(!m_clientMap.contains(identifier));
    Ref generator = AutomaticTranscriptionGenerator::create();
    m_clientMap.add(identifier, makeUnique<TranscriptionService>(WTFMove(generator)));
}

void AutoGeneratedTranscriptionManager::unregisterClient(WebCore::MediaPlayerIdentifier identifier)
{
    ASSERT(m_clientMap.contains(identifier));
    m_clientMap.remove(identifier);
}

void RemoteAudioSourceProviderManager::audioStorageChanged(MediaPlayerIdentifier identifier, ConsumerSharedCARingBuffer::Handle&& handle, const WebCore::CAAudioStreamDescription& description)
{
    auto iterator = m_clientMap.find(identifier);
    if (iterator == m_clientMap.end()) {
        // TODO: Should error.
        return;
    }
    iterator->value->setStorage(WTFMove(handle), description);
}

void RemoteAudioSourceProviderManager::audioSamplesAvailable(MediaPlayerIdentifier identifier, uint64_t startFrame, uint64_t numberOfFrames)
{
    auto iterator = m_clientMap.find(identifier);
    if (iterator == m_clientMap.end()) {
        // TODO: Should error.
        return;
    }
    iterator->value->audioSamplesAvailable(startFrame, numberOfFrames);
}

void AutoGeneratedTranscriptionManager::startTranscription(WebCore::MediaPlayerIdentifier identifier, const String& /* lang */)
{
    ASSERT(m_clientMap.contains(identifier));
    if (iterator == m_clientMap.end()) {
        // TODO: Should error.
        return;
    }
    
    iterator->value->start([ identifier, weakThis = ThreadSafeWeakPtr { *this } ](NSString *text, const WTF::MediaTime start) {
        if (RefPtr protectedThis = weakThis.get()) {
            protectedThis->createAutoGeneratedCaptionCue(identfier, text, start);
        }
    },
       [ identifier, weakThis = ThreadSafeWeakPtr { *this } ](NSString *text, const WTF::MediaTime start) {
           if (RefPtr protectedThis = weakThis.get()) {
               protectedThis->updateAutoGeneratedCaptionCue(identifier, text, start);
           }
       },
       [ identifier, weakThis = ThreadSafeWeakPtr { *this } ] (NSString *text, const WTF::MediaTime start, const WTF::MediaTime end) {
           if (RefPtr protectedThis = weakThis.get()) {
               protectedThis->finalizeAutoGeneratedCaptionCue(text, start, end);
           }
       });
    
    // TODO: Accept languages other than English.
}

void AutoGeneratedTranscriptionManager::stopTranscription(WebCore::MediaPlayerIdentifier identifier)
{
    ASSERT(m_clientMap.contains(identifier));
    if (iterator == m_clientMap.end()) {
        // TODO: Should error.
        return;
    }
    iterator->value->stop();
}

void AutoGeneratedTranscriptionManager::createAutoGeneratedCaptionCue(WebCore::MediaPlayerIdentifier identifier, const String& text, WTF::MediaTime start)
{
    m_connection->send(Messages::AutoGeneratedTranscriptionManagerProxy::createAutoGeneratedCaptionCue(identifier, text, start), 0);
    
    // This function sends a message to the AutoGeneratedTranscriptionManagerProxy.
    // Using the m_sources, the AutoGeneratedTranscriptionManagerProxy will call the appropriate callback to actually create a cue, which should be on the AudioSourceProviderAVFoundationObj object (the value in the sources map).
}

void AutoGeneratedTranscriptionManager::updateAutoGeneratedCaptionCue(WebCore::MediaPlayerIdentifier identifier, const String& text, WTF::MediaTime start)
{
    m_connection->send(Messages::AutoGeneratedTranscriptionManagerProxy::updateAutoGeneratedCaptionCue(identifier, text, start), 0);
}

void AutoGeneratedTranscriptionManager::finalizeAutoGeneratedCaptionCue(WebCore::MediaPlayerIdentifier identifier, const String& text, WTF::MediaTime start, WTF::MediaTime end)
{
    m_connection->send(Messages::AutoGeneratedTranscriptionManagerProxy::finalizeAutoGeneratedCaptionCue(identifier, text, start, end), 0);
}

AutoGeneratedTranscriptionManager::TranscriptionService::TranscriptionService(Ref<AutomaticTranscriptionGenerator>&& generator)
    : m_provider(WTFMove(generator))
{
}

void AutoGeneratedTranscriptionManager::TranscriptionService::setStorage(ConsumerSharedCARingBuffer::Handle&& handle, const WebCore::CAAudioStreamDescription& description)
{
    m_buffer = nullptr;
    handle.takeOwnershipOfMemory(MemoryLedger::Media);
    m_ringBuffer = ConsumerSharedCARingBuffer::map(description, WTFMove(handle));
    if (!m_ringBuffer)
        return;
    m_description = description;
    m_buffer = makeUnique<WebAudioBufferList>(description);
}

void AutoGeneratedTranscriptionManager::TranscriptionService::audioSamplesAvailable(uint64_t startFrame, uint64_t numberOfFrames)
{
    if (!m_buffer) {
        // TODO: Should error.
        return;
    }

    if (!WebAudioBufferList::isSupportedDescription(*m_description, numberOfFrames)) {
        // TODO: Should error.
        return;
    }

    m_buffer->setSampleCount(numberOfFrames);

    m_ringBuffer->fetch(m_buffer->list(), numberOfFrames, startFrame);

    m_transcriptionGenerator->audioSamplesAvailable(m_buffer->list(), *m_description, numberOfFrames);
}

void AutoGeneratedTranscriptionManager::TranscriptionService::start(PartialCaptionCreationTask&& cueCreateCallback, PartialCaptionCreationTask& cueUpdateCallback, CompletedCaptionCreationTask&& cueFinalizeCallback)
{
    m_transcriptionGenerator->prepare(WTFMove(cueCreateCallback), WTFMove(cueUpdateCallback), WTFMove(cueFinalizeCallback));
}

void AutoGeneratedTranscriptionManager::TranscriptionService::stop()
{
    m_transcriptionGenerator->stop();
}

}

#endif
