/*
 * Copyright (C) 2024 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"
#include "AutoGeneratedTranscriptionManagerProxy.h"

#if ENABLE(GPU_PROCESS) && ENABLE(VIDEO)

// #include "AutoGeneratedTranscriptionManagerProxyMessages.h"
#include "AutoGeneratedTranscriptionManagerMessages.h"
#include "GPUProcess.h"
#include "GPUProcessProxyMessages.h"
#include "WebCoreArgumentCoders.h"
#include <WebCore/AudioSourceProviderAVFObjC.h>
#include <WebCore/MediaPlayer.h>
#include <WebCore/MediaPlayerPrivate.h>
#include <WebCore/MediaPlayerIdentifier.h>
#include <wtf/Logger.h>
#include <wtf/UniqueRef.h>

namespace WebKit {

using namespace WebCore;

AutoGeneratedTranscriptionManagerProxy::AutoGeneratedTranscriptionManagerProxy(IPC::Connection* connection)
    : m_connection(connection)
{
    connection->send(Messages::GPUProcessProxy::EnsureAutoGeneratedTranscriptionManager(), 0);
}

void AutoGeneratedTranscriptionManagerProxy::startTranscription(WebCore::MediaPlayerIdentifier identifier, const String& lang)
{
    connection()->send(Messages::AutoGeneratedTranscriptionManager::startTranscription(identifier, lang), 0);
}

void AutoGeneratedTranscriptionManagerProxy::stopTranscription(WebCore::MediaPlayerIdentifier identifier)
{
    connection()->send(Messages::AutoGeneratedTranscriptionManager::stopTranscription(identifier), 0);
}

void AutoGeneratedTranscriptionManagerProxy::createAutoGeneratedCaptionCue(WebCore::MediaPlayerIdentifier identifier, const String& text, WTF::MediaTime start)
{
    ASSERT(m_sources.contains(identifier));
    auto iterator = m_sources.find(identifier);
    if (iterator == m_sources.end()) {
        // TODO: Should error.
        return;
    }
    iterator->value->m_createCompletionHandler(text, start);
}

void AutoGeneratedTranscriptionManagerProxy::updateAutoGeneratedCaptionCue(WebCore::MediaPlayerIdentifier identifier, const String& text, WTF::MediaTime start)
{
    ASSERT(m_sources.contains(identifier));

    auto iterator = m_sources.find(identifier);
    if (iterator == m_sources.end()) {
        // TODO: Should error.
        return;
    }
    iterator->value->m_updateCompletionHandler(text, start);
}

void AutoGeneratedTranscriptionManagerProxy::finalizeAutoGeneratedCaptionCue(WebCore::MediaPlayerIdentifier identifier, const String& text, WTF::MediaTime start, WTF::MediaTime end)
{
    ASSERT(m_sources.contains(identifier));
    
    auto iterator = m_sources.find(identifier);
    if (iterator == m_sources.end()) {
        // TODO: Should error.
        return;
    }
    iterator->value->m_finalizeCompletionHandler(text, start, end);
}

void AutoGeneratedTranscriptionManagerProxy::registerClient(WebCore::MediaPlayerIdentifier identifier, RefPtr<WebCore::AudioSourceProviderAVFObjC> audioSource)
{
    ASSERT(!m_sources.contains(identifier));
    m_sources.add(identifier, audioSource.get());
    connection()->send(Messages::AutoGeneratedTranscriptionManager::RegisterClient(identifier), 0);
}

void AutoGeneratedTranscriptionManagerProxy::unregisterClient(WebCore::MediaPlayerIdentifier identifier)
{
    ASSERT(m_sources.contains(identifier));
    m_sources.remove(identifier);
    connection()->send(Messages::AutoGeneratedTranscriptionManager::UnregisterClient(identifier), 0);
}

} // namespace WebKit

#endif // ENABLE(GPU_PROCESS) && ENABLE(VIDEO)
