/*
 * Copyright (C) 2024 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#include "config.h"
#include "RemoteAutoGeneratedTranscriptionAudioSource.h"

#if ENABLE(GPU_PROCESS) && HAVE(SPEECHRECOGNIZER)

#include "AutoGeneratedTranscriptionManagerProxyMessages.h"
#include <WebCore/AudioSourceProviderAVFObjC.h>

// This class is almost entirely adapted from RemoteAudioSourceProviderProxy.
namespace WebKit {
Ref<RemoteAutoGeneratedTranscriptionAudioSource> RemoteAutoGeneratedTranscriptionAudioSource::create(WebCore::MediaPlayerIdentifier identifier, RefPtr<IPC::Connection>&& connection, WebCore::AudioSourceProviderAVFObjC& localProvider)
{
    auto remoteAudioSource = adoptRef(*new RemoteAutoGeneratedTranscriptionAudioSource(identifier, WTFMove(connection)));

    localAudioSource.setConfigureAudioStorageCallback([remoteAudioSource](auto&&... args) {
        return remoteAudioSource->configureAudioStorage(args...);
    });
    localProvider.setAudioCallback([remoteAudioSource](auto startFrame, auto numberOfFrames) {
        remoteAudioSource->newAudioSamples(startFrame, numberOfFrames);
    });

    return remoteAudioSource;
}

RemoteAutoGeneratedTranscriptionAudioSource::RemoteAutoGeneratedTranscriptionAudioSource(WebCore::MediaPlayerIdentifier identifier, RefPtr<IPC::Connection>&& connection)
    : m_identifier(identifier)
    , m_connection(WTFMove(connection))
{
}

RemoteAutoGeneratedTranscriptionAudioSource::~RemoteAutoGeneratedTranscriptionAudioSource() = default;

std::unique_ptr<WebCore::CARingBuffer> RemoteAutoGeneratedTranscriptionAudioSource::configureAudioStorage(const WebCore::CAAudioStreamDescription& format, size_t frameCount)
{
    auto result = ProducerSharedCARingBuffer::allocate(format, frameCount);
    RELEASE_ASSERT(result); 
        // FIXME(https://bugs.webkit.org/show_bug.cgi?id=262690): Handle allocation failure.
        // This FIXME was present in RemoteAudioSourceProviderProxy.
    auto [ringBuffer, handle] = WTFMove(*result);
    
    m_connection->send(Messages::AutoGeneratedTranscriptionManager::AudioStorageChanged { m_identifier, WTFMove(handle), format }, 0);
    
    std::unique_ptr<WebCore::CARingBuffer> caRingBuffer = WTFMove(ringBuffer);  // NOLINT: see above.
    return caRingBuffer;
}

void RemoteAutoGeneratedTranscriptionAudioSource::newAudioSamples(uint64_t startFrame, uint64_t numberOfFrames)
{
     m_connection->send(Messages::AutoGeneratedTranscriptionManager::AudioSamplesAvailable { m_identifier, startFrame, numberOfFrames }, 0);
}

void RemoteAutoGeneratedTranscriptionAudioSource::setFormat(uint64_t startFrame, uint64_t numberOfFrames)
{
    // TODO: Decide if this function should be implemented.
}

} // namespace WebKit

#endif
