/*
 * Copyright (C) 2024 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS''
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#pragma once
#include "MediaPlayerIdentifier.h"

#include <wtf/CheckedPtr.h>
#include <wtf/MediaTime.h>
#include <wtf/RetainPtr.h>
#include <wtf/WeakPtr.h>


#if ENABLE(VIDEO)

OBJC_CLASS AVAssetTrack;
OBJC_CLASS AVPlayerItem;
OBJC_CLASS AVMutableAudioMix;
OBJC_CLASS AVAudioFormat;
OBJC_CLASS AVAudioPCMBuffer;
OBJC_CLASS CaptionGenerationTask;
OBJC_CLASS SFSpeechAudioBufferRecognitionRequest;
OBJC_CLASS SFSpeechRecognizer;
OBJC_CLASS SFSpeechRecognitionTask;
OBJC_CLASS WebCaptionGenerationTaskRequestDelegate;

typedef struct AudioBufferList AudioBufferList;
typedef struct AudioStreamBasicDescription AudioStreamBasicDescription;

namespace WebCore {

class AutoGeneratedCaptionServer : public CanMakeWeakPtr<AutoGeneratedCaptionServer> {
public:
    using PartialCaptionCreationTask = Function<void(NSString *, const WTF::MediaTime)>;
    using CompletedCaptionCreationTask = Function<void(NSString *, const WTF::MediaTime start, const WTF::MediaTime end)>;
    using MediaPlayerIdentifier = ObjectIdentifier<MediaPlayerIdentifierType>;
    
    AutoGeneratedCaptionServer(MediaPlayerIdentifier identifier);
    void process(AudioBufferList*, const WTF::MediaTime);
        // this is the UIP's area for ring buffer
    void startTranscriptionForMediaPlayer(MediaPlayerIdentifier);
    void stopTranscriptionForMediaPlayer(MediaPlayerIdentifier);
    
    // we can't send this over ipc without a wrapper.
    void setAudioFormat(AudioStreamBasicDescription* asbd);
    
private:
    RetainPtr<SFSpeechRecognizer> m_generator;
    RetainPtr<AVAudioFormat> m_audioProcessingFormat;
    
    RetainPtr<SFSpeechAudioBufferRecognitionRequest> m_samplesBuffer;
    RetainPtr<CaptionGenerationTask> m_generatorRecogitionTask;
    RetainPtr<WebCaptionGenerationTaskRequestDelegate> m_generatorRecognitionTaskDelegate;
    // this may not be necessary

    MediaPlayerIdentifier m_identifier;
    
    // TODO: add support for multiple recognition tasks by mapping media identifier to task, and asking for identifier on each method
    
};

}

#endif
