/*
 * Copyright (C) 2021-2023 Apple Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1.  Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 * 2.  Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY APPLE INC. AND ITS CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL APPLE INC. OR ITS CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#pragma once

#if ENABLE(VIDEO) && ENABLE(GPU_PROCESS)

#include "ArgumentCoders.h"
#include "Connection.h"
#include "MessageNames.h"
#include <WebCore/MediaPlayerIdentifier.h>
#include <wtf/Forward.h>
#include <wtf/ThreadSafeRefCounted.h>
#include <wtf/text/WTFString.h>

namespace WTF {
class MediaTime;
}

namespace Messages {
namespace AutoGeneratedTranscriptionManagerProxy {

static inline IPC::ReceiverName messageReceiverName()
{
    return IPC::ReceiverName::AutoGeneratedTranscriptionManagerProxy;
}

class CreateAutoGeneratedCaptionCue {
public:
    using Arguments = std::tuple<WebCore::MediaPlayerIdentifier, String, WTF::MediaTime>;

    static IPC::MessageName name() { return IPC::MessageName::AutoGeneratedTranscriptionManagerProxy_CreateAutoGeneratedCaptionCue; }
    static constexpr bool isSync = false;
    static constexpr bool canDispatchOutOfOrder = false;
    static constexpr bool replyCanDispatchOutOfOrder = false;

    CreateAutoGeneratedCaptionCue(const WebCore::MediaPlayerIdentifier& identifier, const String& texter, const WTF::MediaTime& start)
        : m_arguments(identifier, texter, start)
    {
    }

    auto&& arguments()
    {
        return WTFMove(m_arguments);
    }

private:
    std::tuple<const WebCore::MediaPlayerIdentifier&, const String&, const WTF::MediaTime&> m_arguments;
};

class UpdateAutoGeneratedCaptionCue {
public:
    using Arguments = std::tuple<WebCore::MediaPlayerIdentifier, String, WTF::MediaTime>;

    static IPC::MessageName name() { return IPC::MessageName::AutoGeneratedTranscriptionManagerProxy_UpdateAutoGeneratedCaptionCue; }
    static constexpr bool isSync = false;
    static constexpr bool canDispatchOutOfOrder = false;
    static constexpr bool replyCanDispatchOutOfOrder = false;

    UpdateAutoGeneratedCaptionCue(const WebCore::MediaPlayerIdentifier& identifier, const String& text, const WTF::MediaTime& start)
        : m_arguments(identifier, text, start)
    {
    }

    auto&& arguments()
    {
        return WTFMove(m_arguments);
    }

private:
    std::tuple<const WebCore::MediaPlayerIdentifier&, const String&, const WTF::MediaTime&> m_arguments;
};

class FinalizeAutoGeneratedCaptionCue {
public:
    using Arguments = std::tuple<WebCore::MediaPlayerIdentifier, String, WTF::MediaTime, WTF::MediaTime>;

    static IPC::MessageName name() { return IPC::MessageName::AutoGeneratedTranscriptionManagerProxy_FinalizeAutoGeneratedCaptionCue; }
    static constexpr bool isSync = false;
    static constexpr bool canDispatchOutOfOrder = false;
    static constexpr bool replyCanDispatchOutOfOrder = false;

    FinalizeAutoGeneratedCaptionCue(const WebCore::MediaPlayerIdentifier& identifier, const String& text, const WTF::MediaTime& start, const WTF::MediaTime& end)
        : m_arguments(identifier, text, start, end)
    {
    }

    auto&& arguments()
    {
        return WTFMove(m_arguments);
    }

private:
    std::tuple<const WebCore::MediaPlayerIdentifier&, const String&, const WTF::MediaTime&, const WTF::MediaTime&> m_arguments;
};

} // namespace AutoGeneratedTranscriptionManagerProxy
} // namespace Messages

#endif // ENABLE(VIDEO) && ENABLE(GPU_PROCESS)
